todoproject/todoapp/urls.py
from . import views
from django.urls import path
app_name = 'todoapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.add, name='add'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('update/<int:task_id>/', views.update, name='update'),
    path('classhome/', views.TodoListview.as_view(), name='classhome'),
    path('classdetail/<int:pk>/', views.TodoDetailView.as_view(), name='classdetail'),
    path('classupdate/<int:pk>/',views.TodoUpdateView.as_view(), name='classupdate'),
    path('classdelete/<int:pk>/', views.TodoDeleteView.as_view(), name='classdelete')

]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.


class ToDo(models.Model):
    title = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.title

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .form import ToDoForm
from .models import ToDo
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
# Create your views here.


def home(request):
    return render(request, 'home.html')


class TodoListview(ListView):
    model = ToDo
    template_name = 'classhome.html'
    context_object_name = 'tasks'


class TodoDetailView(DetailView):
    model = ToDo
    template_name = 'detail.html'
    context_object_name = 'task'


class TodoUpdateView(UpdateView):
    model = ToDo
    template_name = 'classupdate.html'
    context_object_name = 'task'
    fields = ('title','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:classdetail', kwargs={'pk': self.object.id})


class TodoDeleteView(DeleteView):
    model = ToDo
    template_name = 'delete_task.html'
    success_url = reverse_lazy('todoapp:classhome')


def add(request):
    task_list = ToDo.objects.all()
    if request.method == 'POST':
        title = request.POST.get('title')
        priority = request.POST.get('priority')
        date = request.POST.get('date')
        task = ToDo(title=title, priority=priority, date=date)
        task.save()
    return render(request, 'add_task.html', {'tasks': task_list})


def update(request,task_id):
    tasks = ToDo.objects.get(id=task_id)
    form_value = ToDoForm(request.POST or None, instance=tasks)
    if form_value.is_valid():
        form_value.save()
        return redirect('todoapp:add')
    return render(request, 'edit_task.html', {'form': form_value, 'task': tasks})


def delete(request, task_id):
    if request.method == 'POST':
        task_ids = ToDo.objects.get(id=task_id)
        task_ids.delete()
        return redirect('todoapp:add')
    return render(request, 'delete_task.html')

todoproject/templates/add_task.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="banner">
                <div class="banner-text">
                    TODO Application
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Add task here</h3>
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                  <div class="form-group mb-3">
                    <input type="text" name="title" class="form-control" placeholder="Enter Task Title">
                  </div>
                    <div class="form-group mb-3">
                    <input type="text" name="priority" class="form-control" placeholder="Enter Task Priority">
                  </div>
                <div class="form-group mb-3">
                    <input type="date" name="date" class="form-control" placeholder="Enter Task Date">
                  </div>
                    <div class="form-group">
                    <input type="submit" class="btn btn-primary">
                  </div>
            </form>
        </div>
        <div class="col-md-6">
            {%for i in tasks %}
            <div class="card text-white bg-info mb-3 shadow" >
              <div class="card-body">
                <h5 class="card-title">{{ i.title}}</h5>
                <p class="card-text">{{i.priority}}</p>
                  <p class="card-text">{{i.date}}</p>
                <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">DONE</a>
                  <a href="{% url 'todoapp:update' i.id %}" class="btn btn-warning">EDIT</a>
              </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO Application</title>
    <link rel="stylesheet" href="{% static 'style.css'%}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/classhome.html
{% extends 'base.html'%}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="banner">
                <div class="banner-text">
                    TODO Application
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            {%for i in tasks %}
            <div class="card text-white bg-info mb-3 shadow" >
              <div class="card-body">
                <h5 class="card-title">{{ i.title}}</h5>
                <p class="card-text">{{i.priority}}</p>
                  <p class="card-text">{{i.date}}</p>
                <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">DONE</a>
                  <a href="{% url 'todoapp:update' i.id %}" class="btn btn-warning">EDIT</a>
              </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/classupdate.html
{% extends 'base.html'%}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="banner">
                <div class="banner-text">
                    TODO Application
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Edit task here</h3>
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/delete_task.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
  <div class="row">
   <div class="col-md-8 offset-md-2">
    <form method="POST">
      {% csrf_token %}
      <p class="lead">Are you sure to delete this task??</p>
      <input type="submit">
    </form>
  </div>
  </div>
</div>
{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html'%}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="banner">
                <div class="banner-text">
                    TODO Application
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="card text-white bg-info mb-3 shadow" >
              <div class="card-body">
                <h5 class="card-title">{{ task.title}}</h5>
                <p class="card-text">{{task.priority}}</p>
                  <p class="card-text">{{task.date}}</p>
                <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-danger">DONE</a>
                  <a href="{% url 'todoapp:update' task.id %}" class="btn btn-warning">EDIT</a>
              </div>
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/edit_task.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="banner">
                <div class="banner-text">
                    TODO Application
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Edit task here</h3>
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
       <h3>ToDo Application</h3>
        <p class="text-right"><a href="{%url 'todoapp:add' %}">Add Task</a></p>
        </div>
    </div>
</div>
{% endblock %}